networks:
  universalresolver_driver-did-btcr2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.0.0/16
          gateway: 10.2.0.1

services:
  uni-resolver-web:
    container_name: uni-resolver-web
    image: universalresolver/uni-resolver-web:latest
    environment:
      spring.config.location: file:/opt/config/application.yml
    volumes:
      - ./application-universal-resolver.yml:/opt/config/application.yml
    networks:
      default:
    ports:
      - "8080:8080"
  driver-did-btcr2:
    container_name: universalresolver_driver-did-btcr2
    image: universalresolver/driver-did-btcr2:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      uniresolver_driver_did_btcr2_bitcoinConnections: bitcoin;bitcoind;testnet3;bitcoind;signet;esploraelectrsrest;mutinynet;esploraelectrsrest
      uniresolver_driver_did_btcr2_bitcoinConnectionsUrls: bitcoin;http://user:pass@localhost:8332/;testnet3;http://user:pass@localhost:18332/;signet;https://mutinynet.com/api/;mutinynet;https://mutinynet.com/api/
      uniresolver_driver_did_btcr2_bitcoinConnectionsCerts: bitcoin;;testnet3;;signet;;mutinynet;
      uniresolver_driver_did_btcr2_genesisHashes: bitcoin;6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000;testnet3;43497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea330900000000;signet;f61eee3b63a380a477a063af32b2bbc97c9ff9f01f2c4225e973988108000000;mutinynet;f61eee3b63a380a477a063af32b2bbc97c9ff9f01f2c4225e973988108000000
      uniresolver_driver_did_btcr2_ipfs: /ip4/10.2.0.99/tcp/5001
    networks:
      default:
      universalresolver_driver-did-btcr2:
    ports:
      - "18080:8080"
  ipfs:
    container_name: universalresolver_ipfs
    image: ipfs/kubo:release
    networks:
      universalresolver_driver-did-btcr2:
        ipv4_address: 10.2.0.99
