// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: unixfs.proto

package uniresolver.driver.did.btcr2.util.protobuf;

public final class Unixfs {
  private Unixfs() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:uniresolver.driver.did.btcr2.util.protobuf.Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .uniresolver.driver.did.btcr2.util.protobuf.Data.DataType Type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .uniresolver.driver.did.btcr2.util.protobuf.Data.DataType Type = 1;</code>
     */
    uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data.DataType getType();

    /**
     * <code>optional bytes Data = 2;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes Data = 2;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>optional uint64 filesize = 3;</code>
     */
    boolean hasFilesize();
    /**
     * <code>optional uint64 filesize = 3;</code>
     */
    long getFilesize();

    /**
     * <code>repeated uint64 blocksizes = 4;</code>
     */
    java.util.List<Long> getBlocksizesList();
    /**
     * <code>repeated uint64 blocksizes = 4;</code>
     */
    int getBlocksizesCount();
    /**
     * <code>repeated uint64 blocksizes = 4;</code>
     */
    long getBlocksizes(int index);

    /**
     * <code>optional uint64 hashType = 5;</code>
     */
    boolean hasHashType();
    /**
     * <code>optional uint64 hashType = 5;</code>
     */
    long getHashType();

    /**
     * <code>optional uint64 fanout = 6;</code>
     */
    boolean hasFanout();
    /**
     * <code>optional uint64 fanout = 6;</code>
     */
    long getFanout();
  }
  /**
   * Protobuf type {@code uniresolver.driver.did.btcr2.util.protobuf.Data}
   */
  public  static final class Data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:uniresolver.driver.did.btcr2.util.protobuf.Data)
      DataOrBuilder {
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Data() {
      type_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
      filesize_ = 0L;
      blocksizes_ = java.util.Collections.emptyList();
      hashType_ = 0L;
      fanout_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data.DataType value = uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data.DataType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              filesize_ = input.readUInt64();
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                blocksizes_ = new java.util.ArrayList<Long>();
                mutable_bitField0_ |= 0x00000008;
              }
              blocksizes_.add(input.readUInt64());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                blocksizes_ = new java.util.ArrayList<Long>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                blocksizes_.add(input.readUInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              hashType_ = input.readUInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              fanout_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          blocksizes_ = java.util.Collections.unmodifiableList(blocksizes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uniresolver.driver.did.btcr2.util.protobuf.Unixfs.internal_static_com_github_ipfs_tools_proto_unixfs_Data_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uniresolver.driver.did.btcr2.util.protobuf.Unixfs.internal_static_com_github_ipfs_tools_proto_unixfs_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data.class, uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data.Builder.class);
    }

    /**
     * Protobuf enum {@code uniresolver.driver.did.btcr2.util.protobuf.Data.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Raw = 0;</code>
       */
      Raw(0),
      /**
       * <code>Directory = 1;</code>
       */
      Directory(1),
      /**
       * <code>File = 2;</code>
       */
      File(2),
      /**
       * <code>Metadata = 3;</code>
       */
      Metadata(3),
      /**
       * <code>Symlink = 4;</code>
       */
      Symlink(4),
      /**
       * <code>HAMTShard = 5;</code>
       */
      HAMTShard(5),
      ;

      /**
       * <code>Raw = 0;</code>
       */
      public static final int Raw_VALUE = 0;
      /**
       * <code>Directory = 1;</code>
       */
      public static final int Directory_VALUE = 1;
      /**
       * <code>File = 2;</code>
       */
      public static final int File_VALUE = 2;
      /**
       * <code>Metadata = 3;</code>
       */
      public static final int Metadata_VALUE = 3;
      /**
       * <code>Symlink = 4;</code>
       */
      public static final int Symlink_VALUE = 4;
      /**
       * <code>HAMTShard = 5;</code>
       */
      public static final int HAMTShard_VALUE = 5;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return Raw;
          case 1: return Directory;
          case 2: return File;
          case 3: return Metadata;
          case 4: return Symlink;
          case 5: return HAMTShard;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:uniresolver.driver.did.btcr2.util.protobuf.Data.DataType)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required .uniresolver.driver.did.btcr2.util.protobuf.Data.DataType Type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .uniresolver.driver.did.btcr2.util.protobuf.Data.DataType Type = 1;</code>
     */
    public uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data.DataType getType() {
      uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data.DataType result = uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data.DataType.valueOf(type_);
      return result == null ? uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data.DataType.Raw : result;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes Data = 2;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes Data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int FILESIZE_FIELD_NUMBER = 3;
    private long filesize_;
    /**
     * <code>optional uint64 filesize = 3;</code>
     */
    public boolean hasFilesize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint64 filesize = 3;</code>
     */
    public long getFilesize() {
      return filesize_;
    }

    public static final int BLOCKSIZES_FIELD_NUMBER = 4;
    private java.util.List<Long> blocksizes_;
    /**
     * <code>repeated uint64 blocksizes = 4;</code>
     */
    public java.util.List<Long>
        getBlocksizesList() {
      return blocksizes_;
    }
    /**
     * <code>repeated uint64 blocksizes = 4;</code>
     */
    public int getBlocksizesCount() {
      return blocksizes_.size();
    }
    /**
     * <code>repeated uint64 blocksizes = 4;</code>
     */
    public long getBlocksizes(int index) {
      return blocksizes_.get(index);
    }

    public static final int HASHTYPE_FIELD_NUMBER = 5;
    private long hashType_;
    /**
     * <code>optional uint64 hashType = 5;</code>
     */
    public boolean hasHashType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint64 hashType = 5;</code>
     */
    public long getHashType() {
      return hashType_;
    }

    public static final int FANOUT_FIELD_NUMBER = 6;
    private long fanout_;
    /**
     * <code>optional uint64 fanout = 6;</code>
     */
    public boolean hasFanout() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional uint64 fanout = 6;</code>
     */
    public long getFanout() {
      return fanout_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, data_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, filesize_);
      }
      for (int i = 0; i < blocksizes_.size(); i++) {
        output.writeUInt64(4, blocksizes_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(5, hashType_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt64(6, fanout_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, filesize_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < blocksizes_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt64SizeNoTag(blocksizes_.get(i));
        }
        size += dataSize;
        size += 1 * getBlocksizesList().size();
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, hashType_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, fanout_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data)) {
        return super.equals(obj);
      }
      uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data other = (uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      result = result && (hasFilesize() == other.hasFilesize());
      if (hasFilesize()) {
        result = result && (getFilesize()
            == other.getFilesize());
      }
      result = result && getBlocksizesList()
          .equals(other.getBlocksizesList());
      result = result && (hasHashType() == other.hasHashType());
      if (hasHashType()) {
        result = result && (getHashType()
            == other.getHashType());
      }
      result = result && (hasFanout() == other.hasFanout());
      if (hasFanout()) {
        result = result && (getFanout()
            == other.getFanout());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      if (hasFilesize()) {
        hash = (37 * hash) + FILESIZE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFilesize());
      }
      if (getBlocksizesCount() > 0) {
        hash = (37 * hash) + BLOCKSIZES_FIELD_NUMBER;
        hash = (53 * hash) + getBlocksizesList().hashCode();
      }
      if (hasHashType()) {
        hash = (37 * hash) + HASHTYPE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getHashType());
      }
      if (hasFanout()) {
        hash = (37 * hash) + FANOUT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFanout());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code uniresolver.driver.did.btcr2.util.protobuf.Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:uniresolver.driver.did.btcr2.util.protobuf.Data)
        uniresolver.driver.did.btcr2.util.protobuf.Unixfs.DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return uniresolver.driver.did.btcr2.util.protobuf.Unixfs.internal_static_com_github_ipfs_tools_proto_unixfs_Data_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return uniresolver.driver.did.btcr2.util.protobuf.Unixfs.internal_static_com_github_ipfs_tools_proto_unixfs_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data.class, uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data.Builder.class);
      }

      // Construct using uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        filesize_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        blocksizes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        hashType_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        fanout_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return uniresolver.driver.did.btcr2.util.protobuf.Unixfs.internal_static_com_github_ipfs_tools_proto_unixfs_Data_descriptor;
      }

      public uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data getDefaultInstanceForType() {
        return uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data.getDefaultInstance();
      }

      public uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data build() {
        uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data buildPartial() {
        uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data result = new uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.filesize_ = filesize_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          blocksizes_ = java.util.Collections.unmodifiableList(blocksizes_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.blocksizes_ = blocksizes_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.hashType_ = hashType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.fanout_ = fanout_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data) {
          return mergeFrom((uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data other) {
        if (other == uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasFilesize()) {
          setFilesize(other.getFilesize());
        }
        if (!other.blocksizes_.isEmpty()) {
          if (blocksizes_.isEmpty()) {
            blocksizes_ = other.blocksizes_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureBlocksizesIsMutable();
            blocksizes_.addAll(other.blocksizes_);
          }
          onChanged();
        }
        if (other.hasHashType()) {
          setHashType(other.getHashType());
        }
        if (other.hasFanout()) {
          setFanout(other.getFanout());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>required .uniresolver.driver.did.btcr2.util.protobuf.Data.DataType Type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .uniresolver.driver.did.btcr2.util.protobuf.Data.DataType Type = 1;</code>
       */
      public uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data.DataType getType() {
        uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data.DataType result = uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data.DataType.valueOf(type_);
        return result == null ? uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data.DataType.Raw : result;
      }
      /**
       * <code>required .uniresolver.driver.did.btcr2.util.protobuf.Data.DataType Type = 1;</code>
       */
      public Builder setType(uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .uniresolver.driver.did.btcr2.util.protobuf.Data.DataType Type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes Data = 2;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes Data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes Data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes Data = 2;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private long filesize_ ;
      /**
       * <code>optional uint64 filesize = 3;</code>
       */
      public boolean hasFilesize() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint64 filesize = 3;</code>
       */
      public long getFilesize() {
        return filesize_;
      }
      /**
       * <code>optional uint64 filesize = 3;</code>
       */
      public Builder setFilesize(long value) {
        bitField0_ |= 0x00000004;
        filesize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 filesize = 3;</code>
       */
      public Builder clearFilesize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        filesize_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<Long> blocksizes_ = java.util.Collections.emptyList();
      private void ensureBlocksizesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          blocksizes_ = new java.util.ArrayList<Long>(blocksizes_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated uint64 blocksizes = 4;</code>
       */
      public java.util.List<Long>
          getBlocksizesList() {
        return java.util.Collections.unmodifiableList(blocksizes_);
      }
      /**
       * <code>repeated uint64 blocksizes = 4;</code>
       */
      public int getBlocksizesCount() {
        return blocksizes_.size();
      }
      /**
       * <code>repeated uint64 blocksizes = 4;</code>
       */
      public long getBlocksizes(int index) {
        return blocksizes_.get(index);
      }
      /**
       * <code>repeated uint64 blocksizes = 4;</code>
       */
      public Builder setBlocksizes(
          int index, long value) {
        ensureBlocksizesIsMutable();
        blocksizes_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 blocksizes = 4;</code>
       */
      public Builder addBlocksizes(long value) {
        ensureBlocksizesIsMutable();
        blocksizes_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 blocksizes = 4;</code>
       */
      public Builder addAllBlocksizes(
          Iterable<? extends Long> values) {
        ensureBlocksizesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, blocksizes_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 blocksizes = 4;</code>
       */
      public Builder clearBlocksizes() {
        blocksizes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private long hashType_ ;
      /**
       * <code>optional uint64 hashType = 5;</code>
       */
      public boolean hasHashType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint64 hashType = 5;</code>
       */
      public long getHashType() {
        return hashType_;
      }
      /**
       * <code>optional uint64 hashType = 5;</code>
       */
      public Builder setHashType(long value) {
        bitField0_ |= 0x00000010;
        hashType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 hashType = 5;</code>
       */
      public Builder clearHashType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        hashType_ = 0L;
        onChanged();
        return this;
      }

      private long fanout_ ;
      /**
       * <code>optional uint64 fanout = 6;</code>
       */
      public boolean hasFanout() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint64 fanout = 6;</code>
       */
      public long getFanout() {
        return fanout_;
      }
      /**
       * <code>optional uint64 fanout = 6;</code>
       */
      public Builder setFanout(long value) {
        bitField0_ |= 0x00000020;
        fanout_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 fanout = 6;</code>
       */
      public Builder clearFanout() {
        bitField0_ = (bitField0_ & ~0x00000020);
        fanout_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:uniresolver.driver.did.btcr2.util.protobuf.Data)
    }

    // @@protoc_insertion_point(class_scope:uniresolver.driver.did.btcr2.util.protobuf.Data)
    private static final uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data();
    }

    public static uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Data>
        PARSER = new com.google.protobuf.AbstractParser<Data>() {
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Data(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Data> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    public uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MetadataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:uniresolver.driver.did.btcr2.util.protobuf.Metadata)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string MimeType = 1;</code>
     */
    boolean hasMimeType();
    /**
     * <code>optional string MimeType = 1;</code>
     */
    String getMimeType();
    /**
     * <code>optional string MimeType = 1;</code>
     */
    com.google.protobuf.ByteString
        getMimeTypeBytes();
  }
  /**
   * Protobuf type {@code uniresolver.driver.did.btcr2.util.protobuf.Metadata}
   */
  public  static final class Metadata extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:uniresolver.driver.did.btcr2.util.protobuf.Metadata)
      MetadataOrBuilder {
    // Use Metadata.newBuilder() to construct.
    private Metadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Metadata() {
      mimeType_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Metadata(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              mimeType_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uniresolver.driver.did.btcr2.util.protobuf.Unixfs.internal_static_com_github_ipfs_tools_proto_unixfs_Metadata_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uniresolver.driver.did.btcr2.util.protobuf.Unixfs.internal_static_com_github_ipfs_tools_proto_unixfs_Metadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata.class, uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata.Builder.class);
    }

    private int bitField0_;
    public static final int MIMETYPE_FIELD_NUMBER = 1;
    private volatile Object mimeType_;
    /**
     * <code>optional string MimeType = 1;</code>
     */
    public boolean hasMimeType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string MimeType = 1;</code>
     */
    public String getMimeType() {
      Object ref = mimeType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mimeType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string MimeType = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMimeTypeBytes() {
      Object ref = mimeType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mimeType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mimeType_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mimeType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata)) {
        return super.equals(obj);
      }
      uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata other = (uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata) obj;

      boolean result = true;
      result = result && (hasMimeType() == other.hasMimeType());
      if (hasMimeType()) {
        result = result && getMimeType()
            .equals(other.getMimeType());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasMimeType()) {
        hash = (37 * hash) + MIMETYPE_FIELD_NUMBER;
        hash = (53 * hash) + getMimeType().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code uniresolver.driver.did.btcr2.util.protobuf.Metadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:uniresolver.driver.did.btcr2.util.protobuf.Metadata)
        uniresolver.driver.did.btcr2.util.protobuf.Unixfs.MetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return uniresolver.driver.did.btcr2.util.protobuf.Unixfs.internal_static_com_github_ipfs_tools_proto_unixfs_Metadata_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return uniresolver.driver.did.btcr2.util.protobuf.Unixfs.internal_static_com_github_ipfs_tools_proto_unixfs_Metadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata.class, uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata.Builder.class);
      }

      // Construct using uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        mimeType_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return uniresolver.driver.did.btcr2.util.protobuf.Unixfs.internal_static_com_github_ipfs_tools_proto_unixfs_Metadata_descriptor;
      }

      public uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata getDefaultInstanceForType() {
        return uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata.getDefaultInstance();
      }

      public uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata build() {
        uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata buildPartial() {
        uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata result = new uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mimeType_ = mimeType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata) {
          return mergeFrom((uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata other) {
        if (other == uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata.getDefaultInstance()) return this;
        if (other.hasMimeType()) {
          bitField0_ |= 0x00000001;
          mimeType_ = other.mimeType_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object mimeType_ = "";
      /**
       * <code>optional string MimeType = 1;</code>
       */
      public boolean hasMimeType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string MimeType = 1;</code>
       */
      public String getMimeType() {
        Object ref = mimeType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mimeType_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string MimeType = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMimeTypeBytes() {
        Object ref = mimeType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mimeType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string MimeType = 1;</code>
       */
      public Builder setMimeType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        mimeType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string MimeType = 1;</code>
       */
      public Builder clearMimeType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mimeType_ = getDefaultInstance().getMimeType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string MimeType = 1;</code>
       */
      public Builder setMimeTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        mimeType_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:uniresolver.driver.did.btcr2.util.protobuf.Metadata)
    }

    // @@protoc_insertion_point(class_scope:uniresolver.driver.did.btcr2.util.protobuf.Metadata)
    private static final uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata();
    }

    public static uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Metadata>
        PARSER = new com.google.protobuf.AbstractParser<Metadata>() {
      public Metadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Metadata(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Metadata> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Metadata> getParserForType() {
      return PARSER;
    }

    public uniresolver.driver.did.btcr2.util.protobuf.Unixfs.Metadata getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_ipfs_tools_proto_unixfs_Data_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_ipfs_tools_proto_unixfs_Data_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_ipfs_tools_proto_unixfs_Metadata_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_ipfs_tools_proto_unixfs_Metadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014unixfs.proto\022\"com.github.ipfs.tools.pr" +
      "oto.unixfs\"\365\001\n\004Data\022?\n\004Type\030\001 \002(\01621.com." +
      "github.ipfs.tools.proto.unixfs.Data.Data" +
      "Type\022\014\n\004Data\030\002 \001(\014\022\020\n\010filesize\030\003 \001(\004\022\022\n\n" +
      "blocksizes\030\004 \003(\004\022\020\n\010hashType\030\005 \001(\004\022\016\n\006fa" +
      "nout\030\006 \001(\004\"V\n\010DataType\022\007\n\003Raw\020\000\022\r\n\tDirec" +
      "tory\020\001\022\010\n\004File\020\002\022\014\n\010Metadata\020\003\022\013\n\007Symlin" +
      "k\020\004\022\r\n\tHAMTShard\020\005\"\034\n\010Metadata\022\020\n\010MimeTy" +
      "pe\030\001 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_github_ipfs_tools_proto_unixfs_Data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_ipfs_tools_proto_unixfs_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_ipfs_tools_proto_unixfs_Data_descriptor,
        new String[] { "Type", "Data", "Filesize", "Blocksizes", "HashType", "Fanout", });
    internal_static_com_github_ipfs_tools_proto_unixfs_Metadata_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_github_ipfs_tools_proto_unixfs_Metadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_ipfs_tools_proto_unixfs_Metadata_descriptor,
        new String[] { "MimeType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
